Object Repository/Header/HeaderLogoutText.rs
Scripts/SignUp/Script1580979181817.groovy
Scripts/SystemCases/GetCurrentDate/Script1588244768184.groovy
Test Cases/SystemCases/GetCurrentDate.tc
settings/internal/com.kms.katalon.composer.testcase.properties

*Add new services case GetCurrentDate

---

Scripts/GraphQL Coverage/XDigitalCatalog/Products_Sort_Default/Script1609318147671.groovy
settings/internal/com.kms.katalon.composer.testcase.properties

Tests failed in the workflow for the ExperienceAPI repository.
Part of https://virtocommerce.atlassian.net/browse/VP-6514

VP-6514: Fix default sorting (A-Z->0-9)

---

Object Repository/API/backWebServices/Platform module/RestartPlatform.rs
Scripts/API Coverage/Platform/RestartPlatform/Script1613811266227.groovy
Test Cases/API Coverage/Platform/RestartPlatform.tc
Test Suites/Platform_restart.groovy
Test Suites/Platform_restart.ts
settings/internal/com.kms.katalon.composer.testcase.properties

Add restart platform API to check it on GitHub Actions

VP-5660: Add restart platform API

---

Scripts/B2B/System case/WindowsFullSize/Script1600231632950.groovy
Test Suites/B2B/OpenCategoryPage.ts
Test Suites/B2B/RegisterBusinessUser.ts
Test Suites/B2B/RegisterPersonalUser.ts
settings/internal/com.kms.katalon.composer.testcase.properties

remove unnecessary libraries from WindowsFullSize case

VP-7152: fixes WindowsFullSize

---

Scripts/GraphQL Coverage/Core/InitPlatform/Script1609244747171.groovy
Scripts/GraphQL Coverage/Core/Introspection/Script1625663835195.groovy
Test Cases/GraphQL Coverage/Core/Introspection.tc

https://virtocommerce.atlassian.net/browse/PT-2052

PT-2052: Add xAPI introspection test

---

Scripts/API Coverage/CMS_module/moduleContent_blog/Script1626565137993.groovy
Scripts/API Coverage/CMS_module/moduleContent_pages/Script1626560633125.groovy
Scripts/API Coverage/CMS_module/moduleContent_themeUpload/Script1625478749754.groovy

fixes formats for paths to test objects caused errors

VP-7507 : Paths to objects fixed

---

Test Suites/Modules/Platform_collection.ts
Test Suites/Modules/module_Content.groovy
Test Suites/Modules/module_Content.ts
Test Suites/Regressions/Content.groovy
Test Suites/Regressions/Content.ts

Add the suite to "Regression" collection
Add the suite to "Platform" collection

VP-7507 : Regression And Platform collections

---

Scripts/API Coverage/Store/StoreCreate/Script1626423137428.groovy

VP-5646 Some refactoring

---

Object Repository/API/backWebServices/VirtoCommerce.Content/ContentFolderCreate.rs
Object Repository/API/backWebServices/VirtoCommerce.Platform/AssetCreateBlobFolder.rs
Profiles/default.glbl
Scripts/API Coverage/CMS_module/moduleContent_nameValidation/Script1626968994368.groovy
Test Cases/API Coverage/CMS_module/moduleContent_nameValidation.tc
Test Suites/Modules/module_Content.ts
Test Suites/Regressions/Content.ts

Add folderNameListContent variable to glabal variables list
Check name validation for content module
Add the test case to Regression>content and module_Content suites

VP-7507 : Name validation

---

Scripts/API Coverage/ModuleStore/StoreCreate/Script1627405186107.groovy
Scripts/API Coverage/ModuleStore/StoreCreateNameValidation/Script1629364711722.groovy
Scripts/API Coverage/ModuleStore/StoreDelete/Script1629362727065.groovy
Scripts/API Coverage/ModuleStore/StoreSearch/Script1629362705360.groovy
Scripts/API Coverage/ModuleStore/StoreUpdate/Script1629362675455.groovy
Scripts/API Coverage/ModuleStore/StoreUserAccessValidation/Script1629367043082.groovy

Remove 'Object Repository' text from path to test objects

VP-5646: Fix paths to objects

---

Test Cases/API Coverage/ModuleStore/StoreCreateNameValidation.tc
Test Cases/API Coverage/ModuleStore/StoreDelete.tc
Test Cases/API Coverage/ModuleStore/StoreGetAll.tc
Test Cases/API Coverage/ModuleStore/StoreGetById.tc
Test Cases/API Coverage/ModuleStore/StoreSearch.tc
Test Cases/API Coverage/ModuleStore/StoreUpdate.tc
Test Cases/API Coverage/ModuleStore/StoreUserAccessValidation.tc
Test Suites/Modules/Platform_collection.ts
Test Suites/Modules/module_Store.ts

VP-5646: Add suit to the colletction

---

Scripts/API Coverage/ModuleStore/StoreCreate/Script1627405186107.groovy
Test Suites/Modules/module_Store.ts

Fix 'object doesn't exist' isuue

fixing store module cases and suit

---

Test Suites/Modules/Platform_collection.ts
Test Suites/Modules/module_Store.ts

set up store collection

---

Object Repository/API/backWebServices/VirtoCommerce.Platform/ResetPassword.rs
Test Suites/Modules/Platform_collection.ts

- Turn content module suite off in the collection
- Fix verification code for 'API/backWebServices/VirtoCommerce.Customer/Members/MemberSearch' endpoint (change the expected status to 200)

VP-7721: Fix for "customer" suit

---

Test Suites/Modules/Platform_collection.ts
Test Suites/Modules/module_Content.ts

Turn content module on in the collection

VP-7721: Turn content module on in the collection

---

Test Suites/Modules/Platform_collection.ts
Test Suites/Regressions/Catalog.groovy
Test Suites/Regressions/Catalog.ts

- Add module_Catalog suit to regressions folder
- Add module_Catalog suit to collections

VP-7754: module_Catalog suite ready

---

Object Repository/API/backWebServices/VirtoCommerce.Pricing/PriceDeleteById.rs
Object Repository/API/backWebServices/VirtoCommerce.Pricing/PriceForProductInPricelistDelete.rs
Object Repository/API/backWebServices/VirtoCommerce.Pricing/PricelistAssignmentsDelete.rs
Object Repository/API/backWebServices/VirtoCommerce.Pricing/PricelistAssignmentsDeleteFiltered.rs
Object Repository/API/backWebServices/VirtoCommerce.Pricing/PricelistAssignmentsUpdate.rs
Object Repository/API/backWebServices/VirtoCommerce.Pricing/PricelistDelete.rs
Object Repository/API/backWebServices/VirtoCommerce.Pricing/PricelistGetAssignmentById.rs
Object Repository/API/backWebServices/VirtoCommerce.Pricing/PricelistGetAssignments.rs
Object Repository/API/backWebServices/VirtoCommerce.Pricing/PricelistGetNewAssignment.rs
Object Repository/API/backWebServices/VirtoCommerce.Pricing/PricelistUpdate.rs
Object Repository/API/backWebServices/VirtoCommerce.Pricing/PricelistsEvaluate.rs
Object Repository/API/backWebServices/VirtoCommerce.Pricing/PricelistsGet.rs
Object Repository/API/backWebServices/VirtoCommerce.Pricing/PricelistsGetAllForProduct.rs
Object Repository/API/backWebServices/VirtoCommerce.Pricing/PricelistsGetById.rs
Object Repository/API/backWebServices/VirtoCommerce.Pricing/PricesEvaluate.rs
Object Repository/API/backWebServices/VirtoCommerce.Pricing/PricesGetByProductId.rs
Object Repository/API/backWebServices/VirtoCommerce.Pricing/PricesGetWidget.rs
Object Repository/API/backWebServices/VirtoCommerce.Pricing/PricesSearchGet.rs
Object Repository/API/backWebServices/VirtoCommerce.Pricing/PricesSearchPost.rs
Object Repository/API/backWebServices/VirtoCommerce.Pricing/PricesUpdate.rs
Object Repository/API/backWebServices/VirtoCommerce.Pricing/PricesUpdateBulk.rs
Object Repository/API/backWebServices/VirtoCommerce.Pricing/PricesUpdateByProductId.rs

- add objects to objects repo
- add response codes to verifications

VP-7822: pricing module

---

Object Repository/API/backWebServices/VirtoCommerce.Platform/SettingsCreateUpdateDescriptionType.rs
Scripts/API Coverage/ModuleContent/ContentThemeUpload/Script1627405496175.groovy
Scripts/API Coverage/Platform/SettingsUpdateBlacklist/Script1631875575693.groovy

- rewrite unclear comments
- remove unnecessary code
- provide required descriptions

VP-7828: Apply requested improvements

---

Test Suites/Modules/module_Pricing.ts

VP-7831: Pricing module platform

---

Profiles/default.glbl
Scripts/API Coverage/Contacts/EmployeesCreation/Script1601903037023.groovy
Scripts/API Coverage/Contacts/EmployeesUpdateBulk/Script1602666708115.groovy
Scripts/API Coverage/Contacts/MemberGitId/Script1607507814729.groovy
Scripts/API Coverage/Contacts/MemberUpdate/Script1602762296202.groovy
Scripts/API Coverage/Contacts/_module_Customer/contactAddAddress/Script1634230545645.groovy
Scripts/API Coverage/Contacts/_module_Customer/contactAddAddress/Script1634663289889.groovy
Scripts/API Coverage/Contacts/_module_Customer_Member/MemberGitId/Script1634663670395.groovy
Scripts/API Coverage/Contacts/_module_Customer_Member/MemberUpdate/Script1634663654679.groovy
Scripts/API Coverage/ModuleCatalog/productsGetById/Script1633051805427.groovy
Scripts/API Coverage/ModuleContent/ContentMenu/Script1627405463589.groovy
Scripts/API Coverage/ModuleContent/ContentNameValidation/Script1627405471919.groovy
Test Suites/Modules/module_Content.ts
Test Suites/Modules/module_Customer.ts
Test Suites/Modules/module_Customer_Refactored.ts

- Find and replace GlobalVariable.id and GlobalVariable.TEMP

VP-7857: Global variables fix

---

Profiles/default.glbl

- restore missed passwordsListContent global variable

passwordValidationFix

---

Scripts/API Coverage/ModuleSearch/GetIndexForProduct/Script1639572913978.groovy
Scripts/API Coverage/ModuleSearch/indexationRunAndVerify/Script1639644130283.groovy

-add indexDrop after creating a new product

VP-7821: Search index fix

---

Test Suites/Modules/module_Search.ts

VP-7821: Cases off

---

Object Repository/API/backWebServices/VirtoCommerce.Assets/AssetFileUploadLocalStorage.rs
Scripts/API Coverage/Platform/Asset/AssetFileUploadLocalStorage/Script1639750399129.groovy
Test Cases/API Coverage/Platform/Asset/AssetFileUploadLocalStorage.tc
Test Suites/Modules/Platform_collection.ts
Test Suites/Modules/module_Platform_Assets.ts
Test Suites/Regressions/Platform_Assets.ts

- add test case to uploa assets to local storage

VP-7402: Assets upload to local storage

---

Test Suites/Modules/Platform_collection.ts
Test Suites/Modules/module_Platform_Assets.ts

- Turn the suite on in the collection

VP-7402:  Assets upload

---

.gitignore
Data Files/assetsTemplate.json
Object Repository/API/backWebServices/VirtoCommerce.Catalog/ProductUpdate.rs
Profiles/default.glbl
Scripts/API Coverage/ModuleCatalog/assetAddToProduct/Script1640347693601.groovy
Scripts/API Coverage/ModuleCatalog/assetRemoveFromProduct/Script1640347137586.groovy
Scripts/API Coverage/ModuleCatalog/productCreate/Script1633077004686.groovy
Scripts/API Coverage/ModuleCatalog/productUpdate/Script1633077118942.groovy
Test Cases/API Coverage/ModuleCatalog/assetAddToProduct.tc
Test Cases/API Coverage/ModuleCatalog/assetRemoveFromProduct.tc
Test Cases/API Coverage/ModuleCatalog/productUpdate.tc
Test Suites/Modules/module_Catalog_Products.ts

- add test cases to add and remove assets to a product
- add test cases to the module_Catalog_Products

VP-7403: Assets widget  in product

---

Scripts/_DEBUG_FOLDER/_debug_assetFileUpload/Script1640607165342.groovy
Scripts/_DEBUG_FOLDER/_debug_updateProductImage/Script1640607216958.groovy
Test Cases/_DEBUG_FOLDER/.meta
Test Cases/_DEBUG_FOLDER/_debug_assetFileUpload.tc
Test Cases/_DEBUG_FOLDER/_debug_updateProductImage.tc
Test Suites/_DEBUG_FOLDER/ASEETUPLOADIMAGE_DEBUG.groovy
Test Suites/_DEBUG_FOLDER/ASEETUPLOADIMAGE_DEBUG.ts

-use different file than in the initial test
-add temporary siut to check if the issue is resolved

VP-7403: Upload Image debug

---

Test Suites/Modules/module_Catalog_Products.ts

- turn off api cases in module_caralog_products

VP-7403: turn off api cases in module_caralog_products

---

Test Suites/Modules/module_Store.ts

- turn off api cases in storeAssets module suite

VP-7403: turn off api cases in storeAssets module suite

---

Test Suites/Modules/Platform_collection.ts

-  turn on cataloProducts and storeModule in collections

VP-7403: turn on caralog products and store suites in Collections

---

Test Suites/Modules/Platform_collection.ts

VP-7403: Collection fix

---

Data Files/addressDataTemplate.json
Object Repository/API/backWebServices/VirtoCommerce.Customer/Members/MemberCreate.rs
Object Repository/API/backWebServices/VirtoCommerce.Customer/Members/MemberUpdate.rs
Profiles/default.glbl
Scripts/API Coverage/Contacts/_module_Customer_Member/MemberUpdate/Script1634663654679.groovy

- modify 'Object Repository/API/backWebServices/VirtoCommerce.Customer/Members/MemberCreate' (remove hardcoded addresses)
- modify 'Object Repository/API/backWebServices/VirtoCommerce.Customer/Members/MemberUpdate'
- add addresses data bulding code to 'Test Cases/API Coverage/Contacts/_module_Customer_Member/MemberUpdate'
- add addresses verification logic to 'Test Cases/API Coverage/Contacts/_module_Customer_Member/MemberUpdate'

VP-7803: default address flow update

---

Object Repository/API/backWebServices/VirtoCommerce.Marketing/PromoCouponSearch.rs
Scripts/API Coverage/ModuleMarketing/promoCoupon_createUpdateDelete/Script1644408975767.groovy
Scripts/API Coverage/ModuleMarketing/promoUpdate_AlternativeWay/Script1643365759590.groovy

- fix search request to display only relevant results

VP-7906: coupons verification fix

---

Scripts/API Coverage/ModuleOrders/DRAFT.OrderProcessPayment/Script1648190378804.groovy
Test Cases/API Coverage/ModuleOrders/DRAFT.OrderProcessPayment.tc
Test Suites/Modules/Platform_collection.ts

- fix process payment test case

VP-7974: Process payment fix

---

Scripts/API Coverage/ModuleContent/ContentUploadBlacklistCheck/Script1631875401135.groovy
Test Suites/Modules/Platform_collection.ts
Test Suites/Modules/module_Content.ts
Test Suites/Regressions/Content.ts

- update expected error response status code to match the recent platform updates

VP-8068: Content module update

---

Test Suites/Modules/Platform_collection.ts
Test Suites/Modules/module_Platform_ApiKey_userLock.ts

- turn off auth case in apiKey_userLock suit
- move the suit to the start of teh collection

VP-8068:Api key imp

---

Test Suites/Modules/module_Platform_ApiKey_userLock.ts

- turn authorisation test case on in apiKey_userLockj suit

VP-8086:Api key auth on

---

Object Repository/API/backWebServices/VirtoCommerce.Platform/OAuthKeyGenerate.rs

Change the hardcoded url to CI container url variable

VP-8068: Oauth auite fix

---

Object Repository/API/backWebServices/VirtoCommerce.Platform/PushNotificationSearch.rs
Test Suites/Modules/Platform_collection.ts
Test Suites/Modules/module_Platform_PushNotifications.ts

- change push notifications search request body to synchronize with the recent changes

VP-8076: push notifications suit fix

---

Object Repository/API/backWebServices/VirtoCommerce.CatalogPublishing/channelsCreate.rs
Scripts/API Coverage/ModuleCatalogPublishing/channelCreate/Script1649235616271.groovy
Test Suites/DRAFT/DRAFT.module_catalog_Publishing.ts
Test Suites/Modules/Platform_collection.ts

- review catalog publishing module
- add catalog publishing suite to the collection

VP-7988: review and release catalog publishing module coverage

---

Test Suites/Modules/Platform_collection.ts

- remove catalog publishing suite from the collection for further debugging

VP-7988: Cat pub3

---

Test Suites/Modules/Platform_collection.ts
Test Suites/Modules/module_Pricing.ts

- review pricing module coverage code
- run tests in debug actions
- add module to the collection and run it

VP-7822: Pricing module review

---

Object Repository/API/backWebServices/VirtoCommerce.Platform/DynamicPropertyUpdate(cloneInSwagger).rs
Scripts/API Coverage/Platform/DynamicProperties/CustomerModule.Contact/Script1626190113125.groovy
Test Suites/Modules/module_Platform_Dynamic_Properties.ts

- add test object: Object Repository/API/backWebServices/VirtoCommerce.Platform/DynamicPropertyUpdate(cloneInSwagger)
- update code (to cover the added endpoint) at: Test Cases/API Coverage/Platform/DynamicProperties/CustomerModule.Contact

VP-8094: Dynamic Properties update

---

Test Suites/Modules/module_Platform_Dynamic_Properties.ts

- turn off apiKey cases in the dynamic properties suite

VP-8094: Dynamic properties

---

Scripts/API Coverage/ModuleMarketing/PromoAndCoupons/promoUpdate/Script1656944253779.groovy
Test Suites/Modules/Platform_collection.ts
Test Suites/Modules/module_Marketing.ts
Test Suites/Regressions/Marketing.groovy
Test Suites/Regressions/Marketing.ts

- review marketing module promo/coupon coverage
- add marketing module suite to the platform collection/regression folder

VP-7906: marketing module promotion

---

Object Repository/API/backWebServices/VirtoCommerce.Platform/DRAFT/Assets/AssetFileUpload.rs
Object Repository/API/backWebServices/VirtoCommerce.Platform/DRAFT/Assets/AssetFileUploadLocal.rs
Scripts/API Coverage/ModuleMarketing/dynamicContent/ContentPlaceholders/contentPlaceholderUpdate/Script1645149997000.groovy
Test Suites/Modules/Platform_collection.ts
Test Suites/Modules/module_Marketing_dynamicContent.ts
Test Suites/Regressions/Marketing_DynamicContent.groovy
Test Suites/Regressions/Marketing_DynamicContent.ts

- fix urls for asset file upload endpoints:
API/backWebServices/VirtoCommerce.Platform/DRAFT/Assets/AssetFileUpload
API/backWebServices/VirtoCommerce.Platform/DRAFT/Assets/AssetFileUploadLocal
(as assets are no longer a part of the platform module)
- add marketing module dynamic content suite to the collection and to the regression suite

VP-7930: Marketing module dynamic content

---

Object Repository/API/backWebServices/VirtoCommerce.Platform/DynamicPropertyDictionaryItemAddNew(cloneInSwagger).rs
Object Repository/API/backWebServices/VirtoCommerce.Platform/DynamicPropertyDictionaryItemAddNew.rs
Object Repository/API/backWebServices/VirtoCommerce.Platform/DynamicPropertyDictionaryItemDelete(cloneInSwagger).rs
Object Repository/API/backWebServices/VirtoCommerce.Platform/DynamicPropertyDictionaryItemDelete.rs
Object Repository/API/backWebServices/VirtoCommerce.Platform/DynamicPropertyDictionaryItemGet.rs
Object Repository/API/backWebServices/VirtoCommerce.Platform/DynamicPropertyDictionaryItemSearch.rs
Scripts/API Coverage/Platform/DynamicProperties/CustomerModule.ContactNew/Script1657103210342.groovy
Test Cases/API Coverage/Platform/DynamicProperties/CustomerModule.ContactNew.tc

- Add dictionary item objects at:
Object Repository/API/backWebServices/VirtoCommerce.Platform/DynamicPropertyDictionaryItemAddNew
- Add test case:
Test Cases/API Coverage/Platform/DynamicProperties/CustomerModule.ContactNew

VP-8110: Dictionary items

---

Test Suites/Modules/Platform_collection.ts

- debugging platform collection

VP-7601: Secuirity

---

Test Suites/Modules/Platform_collection.ts

- turn off platform-settings suite in the collection

VP-7601: Pass

---

Scripts/API Coverage/ModulePlatform/SettingsGetAll/Script1657947187431.groovy
Test Suites/Modules/Platform_collection.ts
Test Suites/Modules/module_Platform_Settings.ts

- change test case code to verify "Customer" as the default user type in platfom settings at:
Test Cases/API Coverage/ModulePlatform/SettingsGetAll , line 24

VP-7601: ACtualize settings suite
